package services

import (
	"Monitor_Platform/config"
	"Monitor_Platform/snmp"
	"fmt"
	"github.com/gin-gonic/gin"
	"log"
	"sync"
)

var mu sync.Mutex

func GetValueFromOID(c *gin.Context, oid []string) interface{} {
	// Kết nối tới SNMP agent
	err := snmp.Manager.Connect()
	if err != nil {
		log.Printf("Connect() err: %v", err)
		c.Error(err)
	}
	defer snmp.Manager.Conn.Close()

	result, err2 := snmp.Manager.Get(oid) // Lấy dữ liệu từ SNMP agent
	if err2 != nil {
		log.Printf("Get() err: %v", err2)
		c.Error(err)
	}
	return result
}

func GetAllMemInfo(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.MemTotalReal)
	result := int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.MemTotalReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.MemTotalReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.MemTotalReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.MemTotalReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.MemTotalReal)
	result = int64(val.(int))
	sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server109, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server110, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server112, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server113, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server114, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server116, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server117, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server118, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server119, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server120, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server121, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server123, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server124, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server125, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server127, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server128, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server129, config.MemTotalReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	return sum
}

func GetAvailMemInfo(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.MemAvailReal)
	result := int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.MemAvailReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.MemAvailReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.MemAvailReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.MemAvailReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.MemAvailReal)
	result = int64(val.(int))
	sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server109, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server110, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server112, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server113, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server114, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server116, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server117, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server118, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server119, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server120, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server121, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server123, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server124, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server125, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server127, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server128, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server129, config.MemAvailReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	return sum
}

func GetMemCacheInfo(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.MemCacheReal)
	result := int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.MemCacheReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.MemCacheReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.MemCacheReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.MemCacheReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.MemCacheReal)
	result = int64(val.(int))
	sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server109, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server110, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server112, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server113, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server114, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server116, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server117, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server118, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server119, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server120, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server121, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server123, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server124, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server125, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server127, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server128, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server129, config.MemCacheReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	return sum
}

func GetMemBufferInfo(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.MemBufferReal)
	result := int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.MemBufferReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.MemBufferReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.MemBufferReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.MemBufferReal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.MemBufferReal)
	result = int64(val.(int))
	sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server109, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server110, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server112, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server113, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server114, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server116, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server117, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server118, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server119, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server120, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server121, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server123, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server124, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server125, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server127, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server128, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server129, config.MemBufferReal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	return sum
}

func GetCpuRawUser(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.SsCpuRawUser)
	result := int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.SsCpuRawUser)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.SsCpuRawUser)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.SsCpuRawUser)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.SsCpuRawUser)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.SsCpuRawUser)
	result = int64(val.(uint))
	sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server109, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server110, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server112, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server113, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server114, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server116, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server117, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server118, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server119, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server120, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server121, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server123, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server124, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server125, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server127, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server128, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server129, config.SsCpuRawUser)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	return sum
}

func GetCpuRawNice(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.SsCpuRawNice)
	fmt.Printf("102 gia tri %v\n", val)
	result := int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.SsCpuRawNice)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.SsCpuRawNice)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.SsCpuRawNice)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.SsCpuRawNice)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.SsCpuRawNice)
	result = int64(val.(uint))
	sum = append(sum, result)
	return sum
}

func GetCpuRawSystem(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.SsCpuRawSystem)
	fmt.Printf("126 gia tri %v\n", val)
	result := int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.SsCpuRawSystem)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.SsCpuRawSystem)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.SsCpuRawSystem)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.SsCpuRawSystem)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.SsCpuRawSystem)
	result = int64(val.(uint))
	sum = append(sum, result)
	return sum
}

func GetCpuRawIdle(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.SsCpuRawIdle)
	result := int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.SsCpuRawIdle)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.SsCpuRawIdle)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.SsCpuRawIdle)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.SsCpuRawIdle)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.SsCpuRawIdle)
	result = int64(val.(uint))
	sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server109, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server110, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server112, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server113, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server114, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server116, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server117, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server118, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server119, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server120, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server121, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server123, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server124, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server125, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server127, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server128, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server129, config.SsCpuRawIdle)
	//result = int64(val.(uint))
	//sum = append(sum, result)
	return sum
}

func GetCpuRawWait(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.SsCpuRawWait)
	fmt.Printf("174 gia tri %v\n", val)
	result := int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.SsCpuRawWait)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.SsCpuRawWait)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.SsCpuRawWait)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.SsCpuRawWait)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.SsCpuRawWait)
	result = int64(val.(uint))
	sum = append(sum, result)
	return sum
}

func GetCpuRawKernel(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.SsCpuRawKernel)
	fmt.Printf("198 gia tri %v\n", val)
	result := int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.SsCpuRawKernel)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.SsCpuRawKernel)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.SsCpuRawKernel)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.SsCpuRawKernel)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.SsCpuRawKernel)
	result = int64(val.(uint))
	sum = append(sum, result)
	return sum
}

func GetCpuRawInterrupt(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.SsCpuRawInterrupt)
	fmt.Printf("222 gia tri %v\n", val)
	result := int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.SsCpuRawInterrupt)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.SsCpuRawInterrupt)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.SsCpuRawInterrupt)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.SsCpuRawInterrupt)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.SsCpuRawInterrupt)
	result = int64(val.(uint))
	sum = append(sum, result)
	return sum
}

func GetCpuRawSoftIrq(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.SsCpuRawSoftIRQ)
	fmt.Printf("246 gia tri %v\n", val)
	result := int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.SsCpuRawSoftIRQ)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.SsCpuRawSoftIRQ)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.SsCpuRawSoftIRQ)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.SsCpuRawSoftIRQ)
	result = int64(val.(uint))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.SsCpuRawSoftIRQ)
	result = int64(val.(uint))
	sum = append(sum, result)
	return sum
}

func GetDiskTotal(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.DskTotal)
	result := int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.DskTotal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.DskTotal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.DskTotal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.DskTotal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.DskTotal)
	result = int64(val.(int))
	sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server109, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server110, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server112, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server113, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server114, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server116, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server117, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server118, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server119, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server120, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server121, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server123, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server124, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server125, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server127, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server128, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server129, config.DskTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	return sum
}

func GetDiskAvail(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.DskAvail)
	result := int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.DskAvail)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.DskAvail)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.DskAvail)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.DskAvail)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.DskAvail)
	result = int64(val.(int))
	sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server109, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server110, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server112, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server113, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server114, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server116, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server117, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server118, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server119, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server120, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server121, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server123, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server124, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server125, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server127, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server128, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server129, config.DskAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	return sum
}

func GetIoReceiveData(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.IOReceive)
	result := int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.IOReceive)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.IOReceive)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.IOReceive)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.IOReceive)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.IOReceive)
	result = int64(val.(int))
	sum = append(sum, result)
	return sum
}

func GetIoSentData(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.IOSent)
	result := int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.IOSent)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.IOSent)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.IOSent)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.IOSent)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.IOSent)
	result = int64(val.(int))
	sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server109, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server110, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server112, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server113, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server114, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server116, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server117, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server118, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server119, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server120, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server121, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server123, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server124, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server125, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server127, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server128, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server129, config.IOSent)
	//result = int64(val.(int))
	//sum = append(sum, result)
	return sum
}

func GetMemSwapTotal(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.MemSwapTotal)
	result := int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.MemSwapTotal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.MemSwapTotal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.MemSwapTotal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.MemSwapTotal)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.MemSwapTotal)
	result = int64(val.(int))
	sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server109, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server110, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server112, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server113, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server114, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server116, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server117, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server118, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server119, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server120, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server121, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server123, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server124, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server125, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server127, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server128, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server129, config.MemSwapTotal)
	//result = int64(val.(int))
	//sum = append(sum, result)
	return sum
}

func GetMemSwapAvail(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.MemSwapAvail)
	result := int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.MemSwapAvail)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.MemSwapAvail)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.MemSwapAvail)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.MemSwapAvail)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.MemSwapAvail)
	result = int64(val.(int))
	sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server109, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server110, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server112, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server113, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server114, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server116, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server117, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server118, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server119, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server120, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server121, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server123, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server124, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server125, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server127, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server128, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server129, config.MemSwapAvail)
	//result = int64(val.(int))
	//sum = append(sum, result)
	return sum
}

func GetCpuPercentUser(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.SsCpuUser)
	result := int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.SsCpuUser)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.SsCpuUser)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.SsCpuUser)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.SsCpuUser)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.SsCpuUser)
	result = int64(val.(int))
	sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server109, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server110, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server112, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server113, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server114, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server116, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server117, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server118, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server119, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server120, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server121, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server123, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server124, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server125, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server127, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server128, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server129, config.SsCpuUser)
	//result = int64(val.(int))
	//sum = append(sum, result)
	return sum
}

func GetCpuPercentSystem(c *gin.Context) []int64 {
	var sum []int64
	val := GetDataSNMP(c, config.Server244, config.SsCpuSystem)
	result := int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server245, config.SsCpuSystem)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server246, config.SsCpuSystem)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server250, config.SsCpuSystem)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server251, config.SsCpuSystem)
	result = int64(val.(int))
	sum = append(sum, result)
	val = GetDataSNMP(c, config.Server252, config.SsCpuSystem)
	result = int64(val.(int))
	sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server109, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server110, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server112, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server113, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server114, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server116, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server117, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server118, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server119, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server120, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server121, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server123, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server124, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server125, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server127, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server128, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	//val = GetDataSNMP(c, config.Server129, config.SsCpuSystem)
	//result = int64(val.(int))
	//sum = append(sum, result)
	return sum
}

func GetDataSNMP(c *gin.Context, target string, oid string) interface{} {
	mu.Lock()
	defer mu.Unlock()
	var oids []string
	oids = append(oids, oid)
	snmp.Manager.Target = target

	err := snmp.Manager.Connect()
	if err != nil {
		log.Printf("Connect() err: %v", err)
		c.Error(err)
	}
	defer snmp.Manager.Conn.Close()

	result, err2 := snmp.Manager.Get(oids) // Lấy dữ liệu từ SNMP agent
	if err2 != nil {
		log.Printf("Get() err: %v", err2)
		c.Error(err)
	}

	return result.Variables[0].Value
}

func GetPreviousDataSNMP(c *gin.Context, target string, oid string) interface{} {
	mu.Lock()
	defer mu.Unlock()
	var oids []string
	oids = append(oids, oid)
	snmp.Manager.Target = target

	err := snmp.Manager.Connect()
	if err != nil {
		log.Printf("Connect() err: %v", err)
		c.Error(err)
	}
	defer snmp.Manager.Conn.Close()
	result, err2 := snmp.Manager.Get(oids) // Lấy dữ liệu từ SNMP agent
	if err2 != nil {
		log.Printf("Get() err: %v", err2)
		c.Error(err)
	}

	return result.Variables[0].Value
}
